FROM golang:1.21-alpine AS builder

RUN apk add --no-cache ffmpeg ffmpeg-dev pkgconfig gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o viewer-simple cmd/viewer-simple/main.go

FROM alpine:latest
RUN apk add --no-cache ffmpeg
WORKDIR /app
COPY --from=builder /app/viewer-simple .

EXPOSE 8080
CMD ["./viewer-simple"]